### ISSUE TITLE
Chain design image not loading

### ISSUE THREAD

**Issue by kaicode** [IHTSDO/llm-chain-entity-extraction#1]
The chain design image does not load for me:

<img width="431" alt="Screenshot 2023-10-03 at 20 15 17" src="https://github.com/IHTSDO/llm-chain-entity-extraction/assets/2010517/94adf4ee-311e-4485-9fd8-7126e6f50497">

---
When I navigate to the image file I get an access denied message:

<img width="911" alt="Screenshot 2023-10-03 at 20 16 10" src="https://github.com/IHTSDO/llm-chain-entity-extraction/assets/2010517/1b18e08a-abab-46bd-9f23-492cce9ea6e6">

**Comment by alopezo** [comment]
Resolved
