### ISSUE TITLE
Missing requirements.txt file

### ISSUE THREAD

**Issue by HengJayWang** [IHTSDO/llm-chain-entity-extraction#3]
Hi @kaicode,  I want to try this repo and test some SNOMED-CT entity experiments with entity_extractor.py

but I didn't find the requirements.txt so that I can install the related package.

Where can I find that? 🧐  Thanks a lot~

**Comment by kaicode** [comment]
@alopezo do you have a list of npm dependencies and versions for this project? The readme mensions a requirements.txt file, which is a standard way to install these for a Python project, but it's not there.

**Comment by alopezo** [comment]
Thanks, the file has been added

**Comment by alopezo** [comment]
Done
